name: Run Market Data Job

on:
  schedule:
    # Run at 5:00 PM IST on Monday to Friday
    - cron: "0 17 * * 1-5" # 1-5 is to signify on weekdays
  workflow_dispatch: # Allows manual trigger via GitHub Actions UI

jobs:
  run-market-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10" # You can specify the version if required (e.g., 3.8)

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run the script
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          python main.py
